name: Resuable Workflow
on: workflow_call
jobs:
    deploymentboy:
        runs-on: ubuntu-latest

        steps:

         - name: Get Code
           uses: actions/download-artifact@v3
           with:
                name: disc-files   

         - name: Output Information
           run: echo "deploying & uploading..."   